<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Cse Delivery Calc' => 'Калькулятор',
  'Cse Delivery Calc Result' => 'Калькулятор: Результат расчета',
  'Appeal Add' => 'Новое Обращение',
  'Appeal Departament Add' => 'Добавление отдела обращений',
  'Appeal Departament Edit' => 'Редактирование отдела обращений',
  'Appeal Departaments' => 'Отделы обращений',
  'Appeal Edit' => 'Редактирование обращения',
  'Appeal History' => 'История обращения',
  'Appeals' => 'Обращения',
  'Business Center Add' => 'Добавление бизнесс центра',
  'Business Center Edit' => 'Редактирование бизнесс центра',
  'Business Centers' => 'Бизнесс центры',
  'Clean System' => 'Очистка системы',
  'Cse AddressBook' => 'Адресная книга',
  'Cse AddressBook Add' => 'Добавление в адресную книгу',
  'Cse Delivery' => 'Экспресс отправка',
  'Cse Delivery Add' => 'Новый заказ экспресс отправки',
  'Cse Delivery Edit' => 'Редактирование заказа экспресс отправки',
  'Cse Delivery History' => 'Исторя заказа экспресс отправки',
  'Index' => 'Главная',
  'Login' => 'Вход',
  'Post Delivery' => 'Отправка почтой',
  'Post Delivery Add' => 'Новый заказ отправки Почтой России',
  'Post Delivery Edit' => 'Редактирование заказа отправки Почтой России',
  'Post Delivery History' => 'Исторяия заказа отправки Почтой России',
  'Report Create Progress' => 'Генерация отчета',
  'Report Info' => 'Информация об отчете',
  'Report Result' => 'Отчет',
  'Reports' => 'Отчеты',
  'Settings' => 'Настройки',
  'User Add' => 'Новый пользователь',
  'User Edit' => 'Редактирование пользователя',
  'Users' => 'Пользователи',
  'Web Console' => 'WEB Консоль',
);
