<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Cse Delivery Calc' => 'Калькулятор',
  'Cse Delivery Calc Result' => 'Калькулятор: результат расчета',
  'Appeal Add' => 'Создание обращения',
  'Appeal View' => 'Просмотр обращения',
  'Appeals' => 'Обращения',
  'Cse AddressBook' => 'Адресная книга',
  'Cse AddressBook Add' => 'Добавление в адресную книгу',
  'Cse Delivery' => 'Экспресс отправка',
  'Cse Delivery Add' => 'Новый заказ экспресс отправки',
  'Debt limit exceeded' => 'Сумма задолженности превышена',
  'Index' => 'Главная',
  'Post Delivery' => 'Отправка Почтой России',
  'Post Delivery Add' => 'Новый заказ на отправку Почтой России',
  'Profile' => 'Профиль',
);
