<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'mail content {id} {subject} {text} {phone} {email}' =>
    '<p>В ваш отдел поступило обращение № {id}.</p>'."\n".
    '<p>Обращение нужно принять, либо перенаправить обращение в другой отдел.<br />'."\n".
    'Обращение доступно в личном кабинете.</p>'."\n".
    '<p>В ближайшее время нужно обработать, выставить статус и связаться с клиентом!</p>',
  'mail header {id}' => 'Обращение в службу поддержки Офисной Почтовой Службы #{id}',
  'mail subject {id}' => 'Обращение в службу поддержки Офисной Почтовой Службы #{id}',
);
