<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'mail content {email} {changePasswordUrl}' =>
      '<p>Здравствуйте!</p>'."\n".
      '<p>Вы запросили восстановление доступа к личному кабинету Офисной Почтовой Службы<br />'."\n".
      'Для смены пароля к перейдите по ссылке:<br />'."\n".
      '<a href="{changePasswordUrl}">{changePasswordUrl}</a></p>'."\n".
      '<p>В случае если будет выполнен вход на сайт с использованием старого пароля, то ссылка станет недействительной.</p>',
  'mail header' => 'Восстановление пароля в личном кабинете Офисной Почтовой Службы',
  'mail subject' => 'Восстановление пароля в личном кабинете Офисной Почтовой Службы',
);
