<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'mail content {organization} {office} {phone}' =>
      '<p>Ваша заявка на отправку писем принята в работу.</p>'."\n".
      '<p>В ближайшее время с вами свяжется наш курьер.</p>'."\n".
      '<p>В случае невозможности связаться с курьером, пожалуйста, оставьте информацию об этом в Вашем личном кабинете или перезвоните по телефону +7 (495) 646-84-28</p>',

  'mail header' => 'Заявка на отправку писем',
  'mail subject' => 'Заявка на отправку писем',
);
