<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'mail content {id} {subject} {text} {appeal_departament}' =>
    '<p>Благодарим вас за обращение в службу поддержки Офисной Почтовой Службы.</p>'."\n".
    '<p>Ваше обращение, отправленное в отдел "{appeal_departament}" с темой "{subject}", получено.</p>'."\n".
    '<p>Ему присвоен номер "{id}" и, если в дальнейшем Вы'."\n".
    'будете связываться с нами по данному вопросу, просьба его указать.</p>'."\n".
    '<p></p>'."\n".
    '<p>Все письма регистрируются и обрабатываются в порядке очереди, мы'."\n".
    'приступим к решению Вашего вопроса максимально оперативно.<br />'."\n".
    'Как только он будет решен, мы ответим Вам.<br />'."\n".
    'При необходимости в дополнительной информации наш сотрудник '."\n".
    'свяжется с Вами дополнительно.</p>'."\n",
  'mail header {id}' => 'Обращение в службу поддержки Офисной Почтовой Службы #{id}',
  'mail subject {id}' => 'Обращение в службу поддержки Офисной Почтовой Службы #{id}',
);
