<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'mail content {user} {date} {editLink} {waybillLink}' =>
      '<p>Новая заявка на экспресс отправку от {user}.</p>'."\n".
      '<p>Дата: {date}</p>'."\n".
      '<p>Просмотреть и изменить заявку вы можете по ссылке: <a href="{editLink}">{editLink}</a><br />'."\n".
      'После синхронизации заявки накладная будет доступна по ссылке: <a href="{waybillLink}">{waybillLink}</a></p>'."\n",
  'mail header {user}' => 'Заявка на экспересс отправку от {user}',
  'mail subject {user}' => 'Заявка на экспересс отправку от {user}',
);
