<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'appeal_departaments' => 'Отдел',
  'business_center_id' => 'Бизнес центр',
  'id' => '#',
  'status' => 'Статус',
  'status - closed' => 'Закрыто',
  'status - done' => 'Выполнено',
  'status - in work' => 'В работе',
  'status - transfered to departament' => 'Передано в отдел',
  'subject' => 'Тема',
  'text' => 'Обращение',
  'timestamp' => 'Дата',
  'user_id' => 'Пользователь',
);
