<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Status-active' => 'Активирован',
  'Status-banned' => 'Заблокирован',
  'Status-inactive' => 'Не активирован',
  'Type-admin' => 'Администратор',
  'Type-client' => 'Клиент',
  'Type-worker' => 'Сотрудник',
  'additional_email' => 'Дополнительный Email',
  'appeal_departaments' => 'Отделы',
  'auth_key' => 'Ключ',
  'business_centers' => 'Бизнес центры',
  'change_password_key' => 'Ключ',
  'comment' => 'Комментарий',
  'create_time' => 'Дата создания',
  'debt' => 'Задолженность',
  'debt_limit' => 'Лимит задолженности',
  'display' => 'Отображаемое имя',
  'email' => 'Email',
  'email_validate_token' => 'Ключ',
  'id' => 'ID',
  'inn' => 'ИНН',
  'last_login_time' => 'Дата последнего входа',
  'new_password' => 'Новый пароль',
  'old_password' => 'Старый пароль',
  'organization' => 'Организация',
  'password' => 'Пароль',
  'password_hash' => 'Пароль',
  'phone' => 'Телефон',
  'rememberMe' => 'Запомнить меня',
  'security_token' => 'Ключ',
  'status' => 'Статус',
  'type' => 'Тип',
);
