<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'client status - accepted' => 'Заказ принят',
  'client status - deliered' => 'Доставлено',
  'client status - in_work' => 'В работе',
  'client_status' => 'Статус',
  'cargo type - cargo' => 'Груз',
  'cargo type - dangerous documents' => 'Опасный груз',
  'cargo type - documents' => 'Документы',
  'cargo type - oversized cargo' => 'Негабаритный груз',
  'cargo_description' => 'Описание',
  'cargo_height' => 'Высота',
  'cargo_length' => 'Длинна',
  'cargo_seats_number' => 'Число мест',
  'cargo_type' => 'Вид груза',
  'cargo_weight' => 'Вес',
  'cargo_width' => 'Ширина',
  'comment' => 'Примечание',
  'cse_id' => 'CSE ID',
  'customs_currency' => 'Таможенная валюта',
  'customs_value' => 'Таможенная стоимость',
  'declared_value_rate' => 'Объявленная стоимость',
  'delivery method - cod' => 'COD',
  'delivery method - pickup' => 'самовывоз',
  'delivery method - post room' => 'Почтовая комната',
  'delivery method - up doors' => 'До дверей',
  'delivery method - warehouse to door' => 'Склад - Дверь',
  'delivery method - warehouse to warehouse' => 'Склад - Склад',
  'delivery method - with notify' => 'с уведомлением',
  'delivery method - with return' => 'с возвратом',
  'delivery method - with return and notify' => 'с возвратом и уведомлением',
  'delivery_method' => 'Вид доставки',
  'id' => 'ID',
  'insurance_rate' => 'Страхование',
  'notify_email' => 'Email уведомления',
  'notify_phone' => 'Телефон уведомления',
  'payer' => 'Плательщик',
  'payer - customer' => 'Заказчик',
  'payer - receiver' => 'Получатель',
  'payer - sender' => 'Отправитель',
  'payment method - cash' => 'Наличный расчет',
  'payment method - cashless' => 'Безналичный расчет',
  'payment_method' => 'Способ оплаты',
  'price' => 'Цена',
  'recipient' => 'Получатель',
  'recipient_address' => 'Адрес',
  'recipient_city' => 'Город',
  'recipient_contact' => 'Контактное лицо',
  'recipient_email' => 'Email',
  'recipient_info' => 'Информация',
  'recipient_phone' => 'Телефон',
  'recipient_post_index' => 'Индекс',
  'sender' => 'Отправитель',
  'sender_address' => 'Адрес',
  'sender_city' => 'Город',
  'sender_contact' => 'Контактное лицо',
  'sender_email' => 'Email',
  'sender_info' => 'Информация',
  'sender_phone' => 'Телефон',
  'sender_post_index' => 'Индекс',
  'status' => 'Статус',
  'status - not synced' => 'Не синхронизировано',
  'status - not verified' => 'Не проверен',
  'status - sync' => 'Синхронизация',
  'status - synced' => 'Синхронизировано',
  'take_date' => 'Дата забора',
  'take_time_from' => 'Время забора',
  'take_time_to' => 'Время забора',
  'timestamp' => 'Дата',
  'urgency_id' => 'Срочность',
  'user_id' => 'Пользователь',
);
