<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'cse notify appeal departaments' => 'Отделы уведомляемые о новых заявках',
  'allow reset password' => 'Разрешить восстановление пароля',
  'captcha' => 'CAPTCHA',
  'client debt limit page content' => 'Страница превышения задолженности клиента',
  'client index page content' => 'Главная страница клиента',
  'cse company' => 'Компания',
  'cse contact person' => 'Контактное лицо',
  'cse default country' => 'Страна по умолчанию',
  'cse default urgency' => 'Срочность по умолчанию',
  'cse login' => 'Логин',
  'cse password' => 'Пароль',
  'post delivery email list' => 'Список Email адресов',
  'post delivery file types' => 'Типы файлов',
  'post delivery max file size' => 'Максимальный размер файла',
  'worker index page contnet' => 'Главная страница сотрудника',
);
