<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'format' => 'Формат',
  'CSV' => 'CSV',
  'CSV for ms excel' => 'CSV для MS Excel',
  'MS Excel' => 'MS Excel',
  'cse delivery payment method - cash' => 'Оплата наличными',
  'cse delivery payment method - cashless' => 'Оплата безналичным расчетом',
  'endDate' => 'Конечная дата',
  'endMonth' => 'Конечный месяц',
  'payment method' => 'Способ оплаты',
  'period' => 'Период',
  'period - daily' => 'По дням',
  'period - monthly' => 'По месяцам',
  'report' => 'Отчет',
  'report - appeal' => 'Обращения',
  'report - cse delivery count' => 'Доставка - количество заказов',
  'report - cse delivery money' => 'Доставка - сумма заказов',
  'report - post delivery' => 'Доставка почтой России',
  'startDate' => 'Начальная дата',
  'startMonth' => 'Начальный месяц',
);
