<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Cse Delivery Calc' => 'Калькулятор',
  'Appeal Add' => 'Добавить обращение',
  'Appeal Departament Add' => 'Добавить отдел',
  'Appeal Departaments List' => 'Список отделов',
  'Appeals' => 'Обращения',
  'Appeals List' => 'Список обращений',
  'Business Center Add' => 'Добавить бизнесс центр',
  'Business Centers List' => 'Список бизнесс центров',
  'Clean' => 'Очистка системы',
  'Cse Delivery' => 'Экспресс отправка',
  'Cse Delivery Add' => 'Добавить заказ',
  'Cse Delivery List' => 'Список заказов',
  'Login' => 'Вход',
  'Logout' => 'Выход',
  'Post Delivery' => 'Отправка Почтой',
  'Post Delivery Add' => 'Добавить заказ',
  'Post Delivery List' => 'Список заказов',
  'Reports' => 'Отчеты',
  'Settings' => 'Настройки',
  'System' => 'Система',
  'User Add' => 'Добавить пользователя',
  'Users List' => 'Список пользовтелей',
  'Users, BC' => 'Пользователи, БЦ',
  'Web Console' => 'WEB Консоль',
);
