<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Download' => 'Загрузить',
  'Re-create' => 'Создать заново',
  'Report with this parameters alredy exists.<br /><strong>Ready time</strong>: {lastTime}.<br />What you want to do?' => 'Отчет с такими параметрами уже существует.<br />Дата создания отчета: {lastTime}.<br /><br />Что вы хотите сделать?',
  'Your report has ready.' => 'Запрошеный вами отчет создан',
);
