<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Cant synchronize. Cse service returns errors.' => 'Невозможно синхронизировать. Сервис вернул ошибку.',
  'Additional services' => 'Дополнительные услуги',
  'Cant delete. Please wait for the synchronization.' => 'Удаление невозможно. Пожалуйста дождитесь окончания синхронизации.',
  'Cant save. Please wait for the synchronization.' => 'Сохранение невозможно. Пожалуйста дождитесь окончания синхронизации.',
  'Cargo' => 'Груз',
  'Delivery terms' => 'Условия доставки',
  'Dimensions' => 'Габариты',
  'Recipient' => 'Получатель',
  'Sender' => 'Отправитель',
  'Take time' => 'Время забора',
  'download waybill' => 'Загрузить накладную',
  'kg.' => 'кг.',
  'rub.' => 'руб.',
  'time not less 3 hours' => 'Не менее 3х часов',
);
